export {};
declare let x: { a: number } | null;
declare let z: { a: number } | null | undefined;
x.a;
z.a;
x?.a;
null.a;
let q: number = x.a;
declare function el(): { id: string } | null;
el().id;
el()?.id;
declare let fnn: (() => void) | null;
declare let fnu: (() => void) | null | undefined;
fnn();
fnu();
declare let o: { m(): void } | null;
o.m();
o?.m();
const c1: number = null ?? 5;
let k = (null as number | null)!;
const kk: number = k;
declare function either(): { id: string } | null | undefined;
either().id;
