// Generated by scripts/tsc-syntax/generate.py from typescript-go diagnostics_generated.go. Do not edit.

use crate::Message;

#[allow(non_upper_case_globals, dead_code)]
pub const Unterminated_string_literal: &Message = &Message { code: 1002, text: "Unterminated string literal." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected: &Message = &Message { code: 1003, text: "Identifier expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_expected: &Message = &Message { code: 1005, text: "'{0}' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const The_parser_expected_to_find_a_1_to_match_the_0_token_here: &Message = &Message { code: 1007, text: "The parser expected to find a '{1}' to match the '{0}' token here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Trailing_comma_not_allowed: &Message = &Message { code: 1009, text: "Trailing comma not allowed." };
#[allow(non_upper_case_globals, dead_code)]
pub const Asterisk_Slash_expected: &Message = &Message { code: 1010, text: "'*/' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_element_access_expression_should_take_an_argument: &Message = &Message { code: 1011, text: "An element access expression should take an argument." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_token: &Message = &Message { code: 1012, text: "Unexpected token." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_super_must_be_followed_by_an_argument_list_or_member_access: &Message = &Message { code: 1034, text: "'super' must be followed by an argument list or member access." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_token_A_constructor_method_accessor_or_property_was_expected: &Message = &Message { code: 1068, text: "Unexpected token. A constructor, method, accessor, or property was expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Invalid_reference_directive_syntax: &Message = &Message { code: 1084, text: "Invalid 'reference' directive syntax." };
#[allow(non_upper_case_globals, dead_code)]
pub const Invalid_use_of_0_in_strict_mode: &Message = &Message { code: 1100, text: "Invalid use of '{0}' in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_with_statements_are_not_allowed_in_strict_mode: &Message = &Message { code: 1101, text: "'with' statements are not allowed in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_delete_cannot_be_called_on_an_identifier_in_strict_mode: &Message = &Message { code: 1102, text: "'delete' cannot be called on an identifier in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expression_expected: &Message = &Message { code: 1109, text: "Expression expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_expected: &Message = &Message { code: 1110, text: "Type expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Octal_literals_are_not_allowed_Use_the_syntax_0: &Message = &Message { code: 1121, text: "Octal literals are not allowed. Use the syntax '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Variable_declaration_list_cannot_be_empty: &Message = &Message { code: 1123, text: "Variable declaration list cannot be empty." };
#[allow(non_upper_case_globals, dead_code)]
pub const Digit_expected: &Message = &Message { code: 1124, text: "Digit expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Hexadecimal_digit_expected: &Message = &Message { code: 1125, text: "Hexadecimal digit expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_end_of_text: &Message = &Message { code: 1126, text: "Unexpected end of text." };
#[allow(non_upper_case_globals, dead_code)]
pub const Invalid_character: &Message = &Message { code: 1127, text: "Invalid character." };
#[allow(non_upper_case_globals, dead_code)]
pub const Declaration_or_statement_expected: &Message = &Message { code: 1128, text: "Declaration or statement expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Statement_expected: &Message = &Message { code: 1129, text: "Statement expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_case_or_default_expected: &Message = &Message { code: 1130, text: "'case' or 'default' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Property_or_signature_expected: &Message = &Message { code: 1131, text: "Property or signature expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Enum_member_expected: &Message = &Message { code: 1132, text: "Enum member expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Variable_declaration_expected: &Message = &Message { code: 1134, text: "Variable declaration expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Argument_expression_expected: &Message = &Message { code: 1135, text: "Argument expression expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Property_assignment_expected: &Message = &Message { code: 1136, text: "Property assignment expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expression_or_comma_expected: &Message = &Message { code: 1137, text: "Expression or comma expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Parameter_declaration_expected: &Message = &Message { code: 1138, text: "Parameter declaration expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_parameter_declaration_expected: &Message = &Message { code: 1139, text: "Type parameter declaration expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_argument_expected: &Message = &Message { code: 1140, text: "Type argument expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Line_break_not_permitted_here: &Message = &Message { code: 1142, text: "Line break not permitted here." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_or_expected: &Message = &Message { code: 1144, text: "'{' or ';' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_or_JSX_element_expected: &Message = &Message { code: 1145, text: "'{' or JSX element expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Declaration_expected: &Message = &Message { code: 1146, text: "Declaration expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unterminated_template_literal: &Message = &Message { code: 1160, text: "Unterminated template literal." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unterminated_regular_expression_literal: &Message = &Message { code: 1161, text: "Unterminated regular expression literal." };
#[allow(non_upper_case_globals, dead_code)]
pub const Binary_digit_expected: &Message = &Message { code: 1177, text: "Binary digit expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Octal_digit_expected: &Message = &Message { code: 1178, text: "Octal digit expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_token_expected: &Message = &Message { code: 1179, text: "Unexpected token. '{' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Property_destructuring_pattern_expected: &Message = &Message { code: 1180, text: "Property destructuring pattern expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Array_element_destructuring_pattern_expected: &Message = &Message { code: 1181, text: "Array element destructuring pattern expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Modifiers_cannot_appear_here: &Message = &Message { code: 1184, text: "Modifiers cannot appear here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Merge_conflict_marker_encountered: &Message = &Message { code: 1185, text: "Merge conflict marker encountered." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_extended_Unicode_escape_value_must_be_between_0x0_and_0x10FFFF_inclusive: &Message = &Message { code: 1198, text: "An extended Unicode escape value must be between 0x0 and 0x10FFFF inclusive." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unterminated_Unicode_escape_sequence: &Message = &Message { code: 1199, text: "Unterminated Unicode escape sequence." };
#[allow(non_upper_case_globals, dead_code)]
pub const Decorators_are_not_valid_here: &Message = &Message { code: 1206, text: "Decorators are not valid here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Invalid_optional_chain_from_new_expression_Did_you_mean_to_call_0: &Message = &Message { code: 1209, text: "Invalid optional chain from new expression. Did you mean to call '{0}()'?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Code_contained_in_a_class_is_evaluated_in_JavaScript_s_strict_mode_which_does_not_allow_this_use_of_0_For_more_information_see_https_Colon_Slash_Slashdeveloper_mozilla_org_Slashen_US_Slashdocs_SlashWeb_SlashJavaScript_SlashReference_SlashStrict_mode: &Message = &Message { code: 1210, text: "Code contained in a class is evaluated in JavaScript's strict mode which does not allow this use of '{0}'. For more information, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected_0_is_a_reserved_word_in_strict_mode: &Message = &Message { code: 1212, text: "Identifier expected. '{0}' is a reserved word in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected_0_is_a_reserved_word_in_strict_mode_Class_definitions_are_automatically_in_strict_mode: &Message = &Message { code: 1213, text: "Identifier expected. '{0}' is a reserved word in strict mode. Class definitions are automatically in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected_0_is_a_reserved_word_in_strict_mode_Modules_are_automatically_in_strict_mode: &Message = &Message { code: 1214, text: "Identifier expected. '{0}' is a reserved word in strict mode. Modules are automatically in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Invalid_use_of_0_Modules_are_automatically_in_strict_mode: &Message = &Message { code: 1215, text: "Invalid use of '{0}'. Modules are automatically in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_type_predicate_is_only_allowed_in_return_type_position_for_functions_and_methods: &Message = &Message { code: 1228, text: "A type predicate is only allowed in return type position for functions and methods." };
#[allow(non_upper_case_globals, dead_code)]
pub const Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5: &Message = &Message { code: 1250, text: "Function declarations are not allowed inside blocks in strict mode when targeting 'ES5'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5_Class_definitions_are_automatically_in_strict_mode: &Message = &Message { code: 1251, text: "Function declarations are not allowed inside blocks in strict mode when targeting 'ES5'. Class definitions are automatically in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Function_declarations_are_not_allowed_inside_blocks_in_strict_mode_when_targeting_ES5_Modules_are_automatically_in_strict_mode: &Message = &Message { code: 1252, text: "Function declarations are not allowed inside blocks in strict mode when targeting 'ES5'. Modules are automatically in strict mode." };
#[allow(non_upper_case_globals, dead_code)]
pub const Keywords_cannot_contain_escape_characters: &Message = &Message { code: 1260, text: "Keywords cannot contain escape characters." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected_0_is_a_reserved_word_at_the_top_level_of_a_module: &Message = &Message { code: 1262, text: "Identifier expected. '{0}' is a reserved word at the top-level of a module." };
#[allow(non_upper_case_globals, dead_code)]
pub const Global_module_exports_may_only_appear_in_module_files: &Message = &Message { code: 1314, text: "Global module exports may only appear in module files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Global_module_exports_may_only_appear_in_declaration_files: &Message = &Message { code: 1315, text: "Global module exports may only appear in declaration files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Global_module_exports_may_only_appear_at_top_level: &Message = &Message { code: 1316, text: "Global module exports may only appear at top level." };
#[allow(non_upper_case_globals, dead_code)]
pub const String_literal_with_double_quotes_expected: &Message = &Message { code: 1327, text: "String literal with double quotes expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Property_value_can_only_be_string_literal_numeric_literal_true_false_null_object_literal_or_array_literal: &Message = &Message { code: 1328, text: "Property value can only be string literal, numeric literal, 'true', 'false', 'null', object literal or array literal." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_label_is_not_allowed_here: &Message = &Message { code: 1344, text: "A label is not allowed here." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_identifier_or_keyword_cannot_immediately_follow_a_numeric_literal: &Message = &Message { code: 1351, text: "An identifier or keyword cannot immediately follow a numeric literal." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_bigint_literal_cannot_use_exponential_notation: &Message = &Message { code: 1352, text: "A bigint literal cannot use exponential notation." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_bigint_literal_must_be_an_integer: &Message = &Message { code: 1353, text: "A bigint literal must be an integer." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_enum_member_name_must_be_followed_by_a_or: &Message = &Message { code: 1357, text: "An enum member name must be followed by a ',', '=', or '}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_expected_0_is_a_reserved_word_that_cannot_be_used_here: &Message = &Message { code: 1359, text: "Identifier expected. '{0}' is a reserved word that cannot be used here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Did_you_mean_0: &Message = &Message { code: 1369, text: "Did you mean '{0}'?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_token_Did_you_mean_or_rbrace: &Message = &Message { code: 1381, text: "Unexpected token. Did you mean `{'}'}` or `&rbrace;`?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_token_Did_you_mean_or_gt: &Message = &Message { code: 1382, text: "Unexpected token. Did you mean `{'>'}` or `&gt;`?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Function_type_notation_must_be_parenthesized_when_used_in_a_union_type: &Message = &Message { code: 1385, text: "Function type notation must be parenthesized when used in a union type." };
#[allow(non_upper_case_globals, dead_code)]
pub const Constructor_type_notation_must_be_parenthesized_when_used_in_a_union_type: &Message = &Message { code: 1386, text: "Constructor type notation must be parenthesized when used in a union type." };
#[allow(non_upper_case_globals, dead_code)]
pub const Function_type_notation_must_be_parenthesized_when_used_in_an_intersection_type: &Message = &Message { code: 1387, text: "Function type notation must be parenthesized when used in an intersection type." };
#[allow(non_upper_case_globals, dead_code)]
pub const Constructor_type_notation_must_be_parenthesized_when_used_in_an_intersection_type: &Message = &Message { code: 1388, text: "Constructor type notation must be parenthesized when used in an intersection type." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_is_not_allowed_as_a_variable_declaration_name: &Message = &Message { code: 1389, text: "'{0}' is not allowed as a variable declaration name." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_is_not_allowed_as_a_parameter_name: &Message = &Message { code: 1390, text: "'{0}' is not allowed as a parameter name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Neither_decorators_nor_modifiers_may_be_applied_to_this_parameters: &Message = &Message { code: 1433, text: "Neither decorators nor modifiers may be applied to 'this' parameters." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_keyword_or_identifier: &Message = &Message { code: 1434, text: "Unexpected keyword or identifier." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unknown_keyword_or_identifier_Did_you_mean_0: &Message = &Message { code: 1435, text: "Unknown keyword or identifier. Did you mean '{0}'?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Decorators_must_precede_the_name_and_all_keywords_of_property_declarations: &Message = &Message { code: 1436, text: "Decorators must precede the name and all keywords of property declarations." };
#[allow(non_upper_case_globals, dead_code)]
pub const Namespace_must_be_given_a_name: &Message = &Message { code: 1437, text: "Namespace must be given a name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Interface_must_be_given_a_name: &Message = &Message { code: 1438, text: "Interface must be given a name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_alias_must_be_given_a_name: &Message = &Message { code: 1439, text: "Type alias must be given a name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Variable_declaration_not_allowed_at_this_location: &Message = &Message { code: 1440, text: "Variable declaration not allowed at this location." };
#[allow(non_upper_case_globals, dead_code)]
pub const Cannot_start_a_function_call_in_a_type_annotation: &Message = &Message { code: 1441, text: "Cannot start a function call in a type annotation." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_for_property_initializer: &Message = &Message { code: 1442, text: "Expected '=' for property initializer." };
#[allow(non_upper_case_globals, dead_code)]
pub const Module_declaration_names_may_only_use_or_quoted_strings: &Message = &Message { code: 1443, text: "Module declaration names may only use ' or \" quoted strings." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_resolution_mode_should_be_either_require_or_import: &Message = &Message { code: 1453, text: "`resolution-mode` should be either `require` or `import`." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_catch_or_finally_expected: &Message = &Message { code: 1472, text: "'catch' or 'finally' expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_instantiation_expression_cannot_be_followed_by_a_property_access: &Message = &Message { code: 1477, text: "An instantiation expression cannot be followed by a property access." };
#[allow(non_upper_case_globals, dead_code)]
pub const Identifier_or_string_literal_expected: &Message = &Message { code: 1478, text: "Identifier or string literal expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Decorator_used_before_export_here: &Message = &Message { code: 1486, text: "Decorator used before 'export' here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Octal_escape_sequences_are_not_allowed_Use_the_syntax_0: &Message = &Message { code: 1487, text: "Octal escape sequences are not allowed. Use the syntax '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Escape_sequence_0_is_not_allowed: &Message = &Message { code: 1488, text: "Escape sequence '{0}' is not allowed." };
#[allow(non_upper_case_globals, dead_code)]
pub const Decimals_with_leading_zeros_are_not_allowed: &Message = &Message { code: 1489, text: "Decimals with leading zeros are not allowed." };
#[allow(non_upper_case_globals, dead_code)]
pub const File_appears_to_be_binary: &Message = &Message { code: 1490, text: "File appears to be binary." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unknown_regular_expression_flag: &Message = &Message { code: 1499, text: "Unknown regular expression flag." };
#[allow(non_upper_case_globals, dead_code)]
pub const Duplicate_regular_expression_flag: &Message = &Message { code: 1500, text: "Duplicate regular expression flag." };
#[allow(non_upper_case_globals, dead_code)]
pub const This_regular_expression_flag_is_only_available_when_targeting_0_or_later: &Message = &Message { code: 1501, text: "This regular expression flag is only available when targeting '{0}' or later." };
#[allow(non_upper_case_globals, dead_code)]
pub const The_Unicode_u_flag_and_the_Unicode_Sets_v_flag_cannot_be_set_simultaneously: &Message = &Message { code: 1502, text: "The Unicode (u) flag and the Unicode Sets (v) flag cannot be set simultaneously." };
#[allow(non_upper_case_globals, dead_code)]
pub const Named_capturing_groups_are_only_available_when_targeting_ES2018_or_later: &Message = &Message { code: 1503, text: "Named capturing groups are only available when targeting 'ES2018' or later." };
#[allow(non_upper_case_globals, dead_code)]
pub const Subpattern_flags_must_be_present_when_there_is_a_minus_sign: &Message = &Message { code: 1504, text: "Subpattern flags must be present when there is a minus sign." };
#[allow(non_upper_case_globals, dead_code)]
pub const Incomplete_quantifier_Digit_expected: &Message = &Message { code: 1505, text: "Incomplete quantifier. Digit expected." };
#[allow(non_upper_case_globals, dead_code)]
pub const Numbers_out_of_order_in_quantifier: &Message = &Message { code: 1506, text: "Numbers out of order in quantifier." };
#[allow(non_upper_case_globals, dead_code)]
pub const There_is_nothing_available_for_repetition: &Message = &Message { code: 1507, text: "There is nothing available for repetition." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unexpected_0_Did_you_mean_to_escape_it_with_backslash: &Message = &Message { code: 1508, text: "Unexpected '{0}'. Did you mean to escape it with backslash?" };
#[allow(non_upper_case_globals, dead_code)]
pub const This_regular_expression_flag_cannot_be_toggled_within_a_subpattern: &Message = &Message { code: 1509, text: "This regular expression flag cannot be toggled within a subpattern." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_k_must_be_followed_by_a_capturing_group_name_enclosed_in_angle_brackets: &Message = &Message { code: 1510, text: "'\\k' must be followed by a capturing group name enclosed in angle brackets." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_q_is_only_available_inside_character_class: &Message = &Message { code: 1511, text: "'\\q' is only available inside character class." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_c_must_be_followed_by_an_ASCII_letter: &Message = &Message { code: 1512, text: "'\\c' must be followed by an ASCII letter." };
#[allow(non_upper_case_globals, dead_code)]
pub const Undetermined_character_escape: &Message = &Message { code: 1513, text: "Undetermined character escape." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_a_capturing_group_name: &Message = &Message { code: 1514, text: "Expected a capturing group name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Named_capturing_groups_with_the_same_name_must_be_mutually_exclusive_to_each_other: &Message = &Message { code: 1515, text: "Named capturing groups with the same name must be mutually exclusive to each other." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_character_class_range_must_not_be_bounded_by_another_character_class: &Message = &Message { code: 1516, text: "A character class range must not be bounded by another character class." };
#[allow(non_upper_case_globals, dead_code)]
pub const Range_out_of_order_in_character_class: &Message = &Message { code: 1517, text: "Range out of order in character class." };
#[allow(non_upper_case_globals, dead_code)]
pub const Anything_that_would_possibly_match_more_than_a_single_character_is_invalid_inside_a_negated_character_class: &Message = &Message { code: 1518, text: "Anything that would possibly match more than a single character is invalid inside a negated character class." };
#[allow(non_upper_case_globals, dead_code)]
pub const Operators_must_not_be_mixed_within_a_character_class_Wrap_it_in_a_nested_class_instead: &Message = &Message { code: 1519, text: "Operators must not be mixed within a character class. Wrap it in a nested class instead." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_a_class_set_operand: &Message = &Message { code: 1520, text: "Expected a class set operand." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_q_must_be_followed_by_string_alternatives_enclosed_in_braces: &Message = &Message { code: 1521, text: "'\\q' must be followed by string alternatives enclosed in braces." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_character_class_must_not_contain_a_reserved_double_punctuator_Did_you_mean_to_escape_it_with_backslash: &Message = &Message { code: 1522, text: "A character class must not contain a reserved double punctuator. Did you mean to escape it with backslash?" };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_a_Unicode_property_name: &Message = &Message { code: 1523, text: "Expected a Unicode property name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unknown_Unicode_property_name: &Message = &Message { code: 1524, text: "Unknown Unicode property name." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_a_Unicode_property_value: &Message = &Message { code: 1525, text: "Expected a Unicode property value." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unknown_Unicode_property_value: &Message = &Message { code: 1526, text: "Unknown Unicode property value." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_a_Unicode_property_name_or_value: &Message = &Message { code: 1527, text: "Expected a Unicode property name or value." };
#[allow(non_upper_case_globals, dead_code)]
pub const Any_Unicode_property_that_would_possibly_match_more_than_a_single_character_is_only_available_when_the_Unicode_Sets_v_flag_is_set: &Message = &Message { code: 1528, text: "Any Unicode property that would possibly match more than a single character is only available when the Unicode Sets (v) flag is set." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unknown_Unicode_property_name_or_value: &Message = &Message { code: 1529, text: "Unknown Unicode property name or value." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unicode_property_value_expressions_are_only_available_when_the_Unicode_u_flag_or_the_Unicode_Sets_v_flag_is_set: &Message = &Message { code: 1530, text: "Unicode property value expressions are only available when the Unicode (u) flag or the Unicode Sets (v) flag is set." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_must_be_followed_by_a_Unicode_property_value_expression_enclosed_in_braces: &Message = &Message { code: 1531, text: "'\\{0}' must be followed by a Unicode property value expression enclosed in braces." };
#[allow(non_upper_case_globals, dead_code)]
pub const There_is_no_capturing_group_named_0_in_this_regular_expression: &Message = &Message { code: 1532, text: "There is no capturing group named '{0}' in this regular expression." };
#[allow(non_upper_case_globals, dead_code)]
pub const This_backreference_refers_to_a_group_that_does_not_exist_There_are_only_0_capturing_groups_in_this_regular_expression: &Message = &Message { code: 1533, text: "This backreference refers to a group that does not exist. There are only {0} capturing groups in this regular expression." };
#[allow(non_upper_case_globals, dead_code)]
pub const This_backreference_refers_to_a_group_that_does_not_exist_There_are_no_capturing_groups_in_this_regular_expression: &Message = &Message { code: 1534, text: "This backreference refers to a group that does not exist. There are no capturing groups in this regular expression." };
#[allow(non_upper_case_globals, dead_code)]
pub const This_character_cannot_be_escaped_in_a_regular_expression: &Message = &Message { code: 1535, text: "This character cannot be escaped in a regular expression." };
#[allow(non_upper_case_globals, dead_code)]
pub const Octal_escape_sequences_and_backreferences_are_not_allowed_in_a_character_class_If_this_was_intended_as_an_escape_sequence_use_the_syntax_0_instead: &Message = &Message { code: 1536, text: "Octal escape sequences and backreferences are not allowed in a character class. If this was intended as an escape sequence, use the syntax '{0}' instead." };
#[allow(non_upper_case_globals, dead_code)]
pub const Decimal_escape_sequences_and_backreferences_are_not_allowed_in_a_character_class: &Message = &Message { code: 1537, text: "Decimal escape sequences and backreferences are not allowed in a character class." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unicode_escape_sequences_are_only_available_when_the_Unicode_u_flag_or_the_Unicode_Sets_v_flag_is_set: &Message = &Message { code: 1538, text: "Unicode escape sequences are only available when the Unicode (u) flag or the Unicode Sets (v) flag is set." };
#[allow(non_upper_case_globals, dead_code)]
pub const Duplicate_identifier_0: &Message = &Message { code: 2300, text: "Duplicate identifier '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Declaration_name_conflicts_with_built_in_global_identifier_0: &Message = &Message { code: 2397, text: "Declaration name conflicts with built-in global identifier '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Interface_name_cannot_be_0: &Message = &Message { code: 2427, text: "Interface name cannot be '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Cannot_redeclare_block_scoped_variable_0: &Message = &Message { code: 2451, text: "Cannot redeclare block-scoped variable '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_alias_name_cannot_be_0: &Message = &Message { code: 2457, text: "Type alias name cannot be '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_module_cannot_have_multiple_default_exports: &Message = &Message { code: 2528, text: "A module cannot have multiple default exports." };
#[allow(non_upper_case_globals, dead_code)]
pub const Enum_declarations_can_only_merge_with_namespace_or_other_enum_declarations: &Message = &Message { code: 2567, text: "Enum declarations can only merge with namespace or other enum declarations." };
#[allow(non_upper_case_globals, dead_code)]
pub const JSX_expressions_must_have_one_parent_element: &Message = &Message { code: 2657, text: "JSX expressions must have one parent element." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_export_modifier_cannot_be_applied_to_ambient_modules_and_module_augmentations_since_they_are_always_visible: &Message = &Message { code: 2668, text: "'export' modifier cannot be applied to ambient modules and module augmentations since they are always visible." };
#[allow(non_upper_case_globals, dead_code)]
pub const The_first_export_default_is_here: &Message = &Message { code: 2752, text: "The first export default is here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Another_export_default_is_here: &Message = &Message { code: 2753, text: "Another export default is here." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_super_may_not_use_type_arguments: &Message = &Message { code: 2754, text: "'super' may not use type arguments." };
#[allow(non_upper_case_globals, dead_code)]
pub const Declaration_or_statement_expected_This_follows_a_block_of_statements_so_if_you_intended_to_write_a_destructuring_assignment_you_might_need_to_wrap_the_whole_assignment_in_parentheses: &Message = &Message { code: 2809, text: "Declaration or statement expected. This '=' follows a block of statements, so if you intended to write a destructuring assignment, you might need to wrap the whole assignment in parentheses." };
#[allow(non_upper_case_globals, dead_code)]
pub const Namespace_name_cannot_be_0: &Message = &Message { code: 2819, text: "Namespace name cannot be '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Import_assertions_have_been_replaced_by_import_attributes_Use_with_instead_of_assert: &Message = &Message { code: 2880, text: "Import assertions have been replaced by import attributes. Use 'with' instead of 'assert'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Pattern_0_can_have_at_most_one_Asterisk_character: &Message = &Message { code: 5061, text: "Pattern '{0}' can have at most one '*' character." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_is_declared_but_its_value_is_never_read: &Message = &Message { code: 6133, text: "'{0}' is declared but its value is never read." };
#[allow(non_upper_case_globals, dead_code)]
pub const Property_0_is_declared_but_its_value_is_never_read: &Message = &Message { code: 6138, text: "Property '{0}' is declared but its value is never read." };
#[allow(non_upper_case_globals, dead_code)]
pub const Numeric_separators_are_not_allowed_here: &Message = &Message { code: 6188, text: "Numeric separators are not allowed here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Multiple_consecutive_numeric_separators_are_not_permitted: &Message = &Message { code: 6189, text: "Multiple consecutive numeric separators are not permitted." };
#[allow(non_upper_case_globals, dead_code)]
pub const All_imports_in_import_declaration_are_unused: &Message = &Message { code: 6192, text: "All imports in import declaration are unused." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_is_declared_but_never_used: &Message = &Message { code: 6196, text: "'{0}' is declared but never used." };
#[allow(non_upper_case_globals, dead_code)]
pub const All_destructured_elements_are_unused: &Message = &Message { code: 6198, text: "All destructured elements are unused." };
#[allow(non_upper_case_globals, dead_code)]
pub const All_variables_are_unused: &Message = &Message { code: 6199, text: "All variables are unused." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_and_here: &Message = &Message { code: 6204, text: "and here." };
#[allow(non_upper_case_globals, dead_code)]
pub const All_type_parameters_are_unused: &Message = &Message { code: 6205, text: "All type parameters are unused." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_mapped_type_may_not_declare_properties_or_methods: &Message = &Message { code: 7061, text: "A mapped type may not declare properties or methods." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_import_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8002, text: "'import ... =' can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_export_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8003, text: "'export =' can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_parameter_declarations_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8004, text: "Type parameter declarations can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_implements_clauses_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8005, text: "'implements' clauses can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_0_declarations_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8006, text: "'{0}' declarations can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_aliases_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8008, text: "Type aliases can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const The_0_modifier_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8009, text: "The '{0}' modifier can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_annotations_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8010, text: "Type annotations can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_arguments_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8011, text: "Type arguments can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Parameter_modifiers_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8012, text: "Parameter modifiers can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Non_null_assertions_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8013, text: "Non-null assertions can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_assertion_expressions_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8016, text: "Type assertion expressions can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Signature_declarations_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8017, text: "Signature declarations can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Type_satisfaction_expressions_can_only_be_used_in_TypeScript_files: &Message = &Message { code: 8037, text: "Type satisfaction expressions can only be used in TypeScript files." };
#[allow(non_upper_case_globals, dead_code)]
pub const Decorators_may_not_appear_after_export_or_export_default_if_they_also_appear_before_export: &Message = &Message { code: 8038, text: "Decorators may not appear after 'export' or 'export default' if they also appear before 'export'." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_corresponding_JSX_closing_tag_for_0: &Message = &Message { code: 17002, text: "Expected corresponding JSX closing tag for '{0}'." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_unary_expression_with_the_0_operator_is_not_allowed_in_the_left_hand_side_of_an_exponentiation_expression_Consider_enclosing_the_expression_in_parentheses: &Message = &Message { code: 17006, text: "An unary expression with the '{0}' operator is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses." };
#[allow(non_upper_case_globals, dead_code)]
pub const A_type_assertion_expression_is_not_allowed_in_the_left_hand_side_of_an_exponentiation_expression_Consider_enclosing_the_expression_in_parentheses: &Message = &Message { code: 17007, text: "A type assertion expression is not allowed in the left-hand side of an exponentiation expression. Consider enclosing the expression in parentheses." };
#[allow(non_upper_case_globals, dead_code)]
pub const JSX_element_0_has_no_corresponding_closing_tag: &Message = &Message { code: 17008, text: "JSX element '{0}' has no corresponding closing tag." };
#[allow(non_upper_case_globals, dead_code)]
pub const JSX_fragment_has_no_corresponding_closing_tag: &Message = &Message { code: 17014, text: "JSX fragment has no corresponding closing tag." };
#[allow(non_upper_case_globals, dead_code)]
pub const Expected_corresponding_closing_tag_for_JSX_fragment: &Message = &Message { code: 17015, text: "Expected corresponding closing tag for JSX fragment." };
#[allow(non_upper_case_globals, dead_code)]
pub const Unicode_escape_sequence_cannot_appear_here: &Message = &Message { code: 17021, text: "Unicode escape sequence cannot appear here." };
#[allow(non_upper_case_globals, dead_code)]
pub const Private_identifiers_cannot_be_used_as_parameters: &Message = &Message { code: 18009, text: "Private identifiers cannot be used as parameters." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_constructor_is_a_reserved_word: &Message = &Message { code: 18012, text: "'#constructor' is a reserved word." };
#[allow(non_upper_case_globals, dead_code)]
pub const Private_identifiers_are_not_allowed_outside_class_bodies: &Message = &Message { code: 18016, text: "Private identifiers are not allowed outside class bodies." };
#[allow(non_upper_case_globals, dead_code)]
pub const X_can_only_be_used_at_the_start_of_a_file: &Message = &Message { code: 18026, text: "'#!' can only be used at the start of a file." };
#[allow(non_upper_case_globals, dead_code)]
pub const Private_identifiers_are_not_allowed_in_variable_declarations: &Message = &Message { code: 18029, text: "Private identifiers are not allowed in variable declarations." };
#[allow(non_upper_case_globals, dead_code)]
pub const An_optional_chain_cannot_contain_private_identifiers: &Message = &Message { code: 18030, text: "An optional chain cannot contain private identifiers." };
