// Generated by scripts/api/generate-enums.ts from typescript@6.0.3. Do not edit.
// TypeScript's node kind guards: each accepts exactly these `SyntaxKind`s.
"use strict";

module.exports = {
	"isAccessor": [
		178,
		179
	],
	"isArrayBindingElement": [
		209,
		233
	],
	"isArrayBindingPattern": [
		208
	],
	"isArrayLiteralExpression": [
		210
	],
	"isArrayTypeNode": [
		189
	],
	"isArrowFunction": [
		220
	],
	"isAsExpression": [
		235
	],
	"isAssertClause": [
		301
	],
	"isAssertEntry": [
		302
	],
	"isAssertionExpression": [
		217,
		235
	],
	"isAssertsKeyword": [
		131
	],
	"isAsteriskToken": [
		42
	],
	"isAwaitExpression": [
		224
	],
	"isAwaitKeyword": [
		135
	],
	"isBigIntLiteral": [
		10
	],
	"isBinaryExpression": [
		227
	],
	"isBinaryOperatorToken": [
		28,
		30,
		32,
		33,
		34,
		35,
		36,
		37,
		38,
		40,
		41,
		42,
		43,
		44,
		45,
		48,
		49,
		50,
		51,
		52,
		53,
		56,
		57,
		61,
		64,
		65,
		66,
		67,
		68,
		69,
		70,
		71,
		72,
		73,
		74,
		75,
		76,
		77,
		78,
		79,
		103,
		104
	],
	"isBindingElement": [
		209
	],
	"isBindingName": [
		80,
		207,
		208
	],
	"isBlock": [
		242
	],
	"isBreakOrContinueStatement": [
		252,
		253
	],
	"isBreakStatement": [
		253
	],
	"isBundle": [
		309
	],
	"isCallExpression": [
		214
	],
	"isCallOrNewExpression": [
		214,
		215
	],
	"isCallSignatureDeclaration": [
		180
	],
	"isCaseBlock": [
		270
	],
	"isCaseClause": [
		297
	],
	"isCaseOrDefaultClause": [
		297,
		298
	],
	"isCatchClause": [
		300
	],
	"isClassDeclaration": [
		264
	],
	"isClassElement": [
		173,
		175,
		176,
		177,
		178,
		179,
		182,
		241
	],
	"isClassExpression": [
		232
	],
	"isClassLike": [
		232,
		264
	],
	"isClassOrTypeElement": [
		172,
		173,
		174,
		175,
		176,
		177,
		178,
		179,
		180,
		181,
		182,
		241,
		355
	],
	"isClassStaticBlockDeclaration": [
		176
	],
	"isColonToken": [
		59
	],
	"isCommaListExpression": [
		357
	],
	"isComputedPropertyName": [
		168
	],
	"isConditionalExpression": [
		228
	],
	"isConditionalTypeNode": [
		195
	],
	"isConstructSignatureDeclaration": [
		181
	],
	"isConstructorDeclaration": [
		177
	],
	"isConstructorTypeNode": [
		186
	],
	"isContinueStatement": [
		252
	],
	"isDebuggerStatement": [
		260
	],
	"isDeclarationStatement": [
		263,
		264,
		265,
		266,
		267,
		268,
		271,
		272,
		273,
		278,
		279,
		283
	],
	"isDecorator": [
		171
	],
	"isDefaultClause": [
		298
	],
	"isDeleteExpression": [
		221
	],
	"isDoStatement": [
		247
	],
	"isDotDotDotToken": [
		26
	],
	"isElementAccessExpression": [
		213
	],
	"isEmptyStatement": [
		243
	],
	"isEntityName": [
		80,
		167
	],
	"isEnumDeclaration": [
		267
	],
	"isEnumMember": [
		307
	],
	"isEqualsGreaterThanToken": [
		39
	],
	"isExclamationToken": [
		54
	],
	"isExportAssignment": [
		278
	],
	"isExportDeclaration": [
		279
	],
	"isExportSpecifier": [
		282
	],
	"isExpressionStatement": [
		245
	],
	"isExpressionWithTypeArguments": [
		234
	],
	"isExternalModuleReference": [
		284
	],
	"isForInStatement": [
		250
	],
	"isForOfStatement": [
		251
	],
	"isForStatement": [
		249
	],
	"isFunctionDeclaration": [
		263
	],
	"isFunctionExpression": [
		219
	],
	"isFunctionOrConstructorTypeNode": [
		185,
		186
	],
	"isFunctionTypeNode": [
		185
	],
	"isGetAccessor": [
		178
	],
	"isGetAccessorDeclaration": [
		178
	],
	"isHeritageClause": [
		299
	],
	"isIdentifier": [
		80
	],
	"isIdentifierOrThisTypeNode": [
		80,
		198
	],
	"isIfStatement": [
		246
	],
	"isImportAttribute": [
		302
	],
	"isImportAttributeName": [
		11,
		80
	],
	"isImportAttributes": [
		301
	],
	"isImportClause": [
		274
	],
	"isImportDeclaration": [
		273
	],
	"isImportEqualsDeclaration": [
		272
	],
	"isImportOrExportSpecifier": [
		277,
		282
	],
	"isImportSpecifier": [
		277
	],
	"isImportTypeAssertionContainer": [
		303
	],
	"isImportTypeNode": [
		206
	],
	"isIndexSignatureDeclaration": [
		182
	],
	"isIndexedAccessTypeNode": [
		200
	],
	"isInferTypeNode": [
		196
	],
	"isInterfaceDeclaration": [
		265
	],
	"isIntersectionTypeNode": [
		194
	],
	"isJSDoc": [
		321
	],
	"isJSDocAllType": [
		313
	],
	"isJSDocAugmentsTag": [
		329
	],
	"isJSDocAuthorTag": [
		331
	],
	"isJSDocCallbackTag": [
		339
	],
	"isJSDocClassTag": [
		333
	],
	"isJSDocDeprecatedTag": [
		332
	],
	"isJSDocEnumTag": [
		341
	],
	"isJSDocFunctionType": [
		318
	],
	"isJSDocImplementsTag": [
		330
	],
	"isJSDocImportTag": [
		352
	],
	"isJSDocLink": [
		325
	],
	"isJSDocLinkCode": [
		326
	],
	"isJSDocLinkLike": [
		325,
		326,
		327
	],
	"isJSDocLinkPlain": [
		327
	],
	"isJSDocMemberName": [
		312
	],
	"isJSDocNameReference": [
		311
	],
	"isJSDocNamepathType": [
		320
	],
	"isJSDocNonNullableType": [
		316
	],
	"isJSDocNullableType": [
		315
	],
	"isJSDocOptionalType": [
		317
	],
	"isJSDocOverloadTag": [
		340
	],
	"isJSDocOverrideTag": [
		338
	],
	"isJSDocParameterTag": [
		342
	],
	"isJSDocPrivateTag": [
		335
	],
	"isJSDocPropertyLikeTag": [
		342,
		349
	],
	"isJSDocPropertyTag": [
		349
	],
	"isJSDocProtectedTag": [
		336
	],
	"isJSDocPublicTag": [
		334
	],
	"isJSDocReadonlyTag": [
		337
	],
	"isJSDocReturnTag": [
		343
	],
	"isJSDocSatisfiesTag": [
		351
	],
	"isJSDocSeeTag": [
		348
	],
	"isJSDocSignature": [
		324
	],
	"isJSDocTemplateTag": [
		346
	],
	"isJSDocThisTag": [
		344
	],
	"isJSDocThrowsTag": [
		350
	],
	"isJSDocTypeExpression": [
		310
	],
	"isJSDocTypeLiteral": [
		323
	],
	"isJSDocTypeTag": [
		345
	],
	"isJSDocTypedefTag": [
		347
	],
	"isJSDocUnknownTag": [
		328
	],
	"isJSDocUnknownType": [
		314
	],
	"isJSDocVariadicType": [
		319
	],
	"isJsxAttribute": [
		292
	],
	"isJsxAttributeLike": [
		292,
		294
	],
	"isJsxAttributes": [
		293
	],
	"isJsxCallLike": [
		286,
		287,
		290
	],
	"isJsxChild": [
		12,
		285,
		286,
		289,
		295
	],
	"isJsxClosingElement": [
		288
	],
	"isJsxClosingFragment": [
		291
	],
	"isJsxElement": [
		285
	],
	"isJsxExpression": [
		295
	],
	"isJsxFragment": [
		289
	],
	"isJsxNamespacedName": [
		296
	],
	"isJsxOpeningElement": [
		287
	],
	"isJsxOpeningFragment": [
		290
	],
	"isJsxOpeningLikeElement": [
		286,
		287
	],
	"isJsxSelfClosingElement": [
		286
	],
	"isJsxSpreadAttribute": [
		294
	],
	"isJsxTagNameExpression": [
		80,
		110,
		212,
		296
	],
	"isJsxText": [
		12
	],
	"isLabeledStatement": [
		257
	],
	"isLiteralExpression": [
		9,
		10,
		11,
		12,
		13,
		14,
		15
	],
	"isLiteralTypeLiteral": [
		9,
		10,
		11,
		12,
		13,
		14,
		15,
		97,
		106,
		112,
		225
	],
	"isLiteralTypeNode": [
		202
	],
	"isMappedTypeNode": [
		201
	],
	"isMemberName": [
		80,
		81
	],
	"isMetaProperty": [
		237
	],
	"isMethodDeclaration": [
		175
	],
	"isMethodSignature": [
		174
	],
	"isMinusToken": [
		41
	],
	"isMissingDeclaration": [
		283
	],
	"isModifier": [
		87,
		90,
		95,
		103,
		123,
		124,
		125,
		126,
		128,
		129,
		134,
		138,
		147,
		148,
		164
	],
	"isModifierLike": [
		87,
		90,
		95,
		103,
		123,
		124,
		125,
		126,
		128,
		129,
		134,
		138,
		147,
		148,
		164,
		171
	],
	"isModuleBlock": [
		269
	],
	"isModuleBody": [
		80,
		268,
		269
	],
	"isModuleDeclaration": [
		268
	],
	"isModuleExportName": [
		11,
		80
	],
	"isModuleName": [
		11,
		80
	],
	"isModuleReference": [
		80,
		167,
		284
	],
	"isNamedExportBindings": [
		280,
		281
	],
	"isNamedExports": [
		280
	],
	"isNamedImportBindings": [
		275,
		276
	],
	"isNamedImports": [
		276
	],
	"isNamedTupleMember": [
		203
	],
	"isNamespaceExport": [
		281
	],
	"isNamespaceExportDeclaration": [
		271
	],
	"isNamespaceImport": [
		275
	],
	"isNewExpression": [
		215
	],
	"isNoSubstitutionTemplateLiteral": [
		15
	],
	"isNonNullExpression": [
		236
	],
	"isNotEmittedStatement": [
		354
	],
	"isNumericLiteral": [
		9
	],
	"isObjectBindingPattern": [
		207
	],
	"isObjectLiteralElement": [
		175,
		178,
		179,
		292,
		294,
		304,
		305,
		306
	],
	"isObjectLiteralElementLike": [
		175,
		178,
		179,
		304,
		305,
		306
	],
	"isObjectLiteralExpression": [
		211
	],
	"isOmittedExpression": [
		233
	],
	"isOptionalTypeNode": [
		191
	],
	"isParameter": [
		170
	],
	"isParenthesizedExpression": [
		218
	],
	"isParenthesizedTypeNode": [
		197
	],
	"isPartiallyEmittedExpression": [
		356
	],
	"isPlusToken": [
		40
	],
	"isPostfixUnaryExpression": [
		226
	],
	"isPrefixUnaryExpression": [
		225
	],
	"isPrivateIdentifier": [
		81
	],
	"isPropertyAccessExpression": [
		212
	],
	"isPropertyAccessOrQualifiedName": [
		167,
		212
	],
	"isPropertyAssignment": [
		304
	],
	"isPropertyDeclaration": [
		173
	],
	"isPropertyName": [
		9,
		11,
		80,
		81,
		168
	],
	"isPropertySignature": [
		172
	],
	"isQualifiedName": [
		167
	],
	"isQuestionDotToken": [
		29
	],
	"isQuestionOrExclamationToken": [
		54,
		58
	],
	"isQuestionOrPlusOrMinusToken": [
		40,
		41,
		58
	],
	"isQuestionToken": [
		58
	],
	"isReadonlyKeywordOrPlusOrMinusToken": [
		40,
		41,
		148
	],
	"isRegularExpressionLiteral": [
		14
	],
	"isRestTypeNode": [
		192
	],
	"isReturnStatement": [
		254
	],
	"isSatisfiesExpression": [
		239
	],
	"isSemicolonClassElement": [
		241
	],
	"isSetAccessor": [
		179
	],
	"isSetAccessorDeclaration": [
		179
	],
	"isShorthandPropertyAssignment": [
		305
	],
	"isSourceFile": [
		308
	],
	"isSpreadAssignment": [
		306
	],
	"isSpreadElement": [
		231
	],
	"isStatement": [
		242,
		243,
		244,
		245,
		246,
		247,
		248,
		249,
		250,
		251,
		252,
		253,
		254,
		255,
		256,
		257,
		258,
		259,
		260,
		263,
		264,
		265,
		266,
		267,
		268,
		271,
		272,
		273,
		278,
		279,
		283,
		354
	],
	"isStringLiteral": [
		11
	],
	"isStringLiteralOrJsxExpression": [
		11,
		295
	],
	"isStringTextContainingNode": [
		11,
		15,
		16,
		17,
		18
	],
	"isSwitchStatement": [
		256
	],
	"isSyntheticExpression": [
		238
	],
	"isTaggedTemplateExpression": [
		216
	],
	"isTemplateExpression": [
		229
	],
	"isTemplateHead": [
		16
	],
	"isTemplateLiteral": [
		15,
		229
	],
	"isTemplateLiteralToken": [
		15,
		16,
		17,
		18
	],
	"isTemplateLiteralTypeNode": [
		204
	],
	"isTemplateLiteralTypeSpan": [
		205
	],
	"isTemplateMiddle": [
		17
	],
	"isTemplateMiddleOrTemplateTail": [
		17,
		18
	],
	"isTemplateSpan": [
		240
	],
	"isTemplateTail": [
		18
	],
	"isThisTypeNode": [
		198
	],
	"isThrowStatement": [
		258
	],
	"isTryStatement": [
		259
	],
	"isTupleTypeNode": [
		190
	],
	"isTypeAliasDeclaration": [
		266
	],
	"isTypeAssertionExpression": [
		217
	],
	"isTypeElement": [
		172,
		174,
		178,
		179,
		180,
		181,
		182,
		355
	],
	"isTypeLiteralNode": [
		188
	],
	"isTypeNode": [
		116,
		133,
		136,
		141,
		146,
		150,
		151,
		154,
		155,
		157,
		159,
		163,
		183,
		184,
		185,
		186,
		187,
		188,
		189,
		190,
		191,
		192,
		193,
		194,
		195,
		196,
		197,
		198,
		199,
		200,
		201,
		202,
		203,
		204,
		205,
		206,
		234,
		313,
		314,
		315,
		316,
		317,
		318,
		319
	],
	"isTypeOfExpression": [
		222
	],
	"isTypeOperatorNode": [
		199
	],
	"isTypeParameterDeclaration": [
		169
	],
	"isTypePredicateNode": [
		183
	],
	"isTypeQueryNode": [
		187
	],
	"isTypeReferenceNode": [
		184
	],
	"isUnionTypeNode": [
		193
	],
	"isVariableDeclaration": [
		261
	],
	"isVariableDeclarationList": [
		262
	],
	"isVariableStatement": [
		244
	],
	"isVoidExpression": [
		223
	],
	"isWhileStatement": [
		248
	],
	"isWithStatement": [
		255
	],
	"isYieldExpression": [
		230
	]
};
