use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::{env, fs};

/// Generates the embedded standard-library table from the vendored TypeScript
/// snapshot in `generated-libs/`.
///
/// The table stores each file's text via `include_str!`, so the bytes land in
/// the binary's read-only data and no `generated-libs` directory has to exist at
/// runtime. Emitting the table from a build script (rather than hand-writing one
/// `include_str!` per lib) keeps it in sync with whatever the vendor-update
/// workflow checked in.
fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let lib_dir = manifest_dir.join("generated-libs");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", lib_dir.display());

    let mut libs = collect_lib_files(&lib_dir);
    // Sorting makes the generated table byte-identical across machines, whose
    // directory iteration order differs.
    libs.sort();

    let version = read_pinned_version(&lib_dir.join("manifest.json"));

    let mut generated = String::new();
    generated.push_str("// @generated by build.rs from generated-libs/. Do not edit.\n");
    let _ = writeln!(
        generated,
        "pub const BUNDLED_TYPESCRIPT_VERSION: &str = {version:?};"
    );
    generated.push_str("pub static EMBEDDED_LIBS: &[EmbeddedLib] = &[\n");
    for lib in &libs {
        let path = lib_dir.join(format!("lib.{lib}.d.ts"));
        println!("cargo:rerun-if-changed={}", path.display());
        let _ = writeln!(
            generated,
            "    EmbeddedLib {{ name: {lib:?}, source: include_str!({:?}) }},",
            path.to_string_lossy()
        );
    }
    generated.push_str("];\n");

    let out_path = out_dir.join("embedded_libs.rs");
    fs::write(&out_path, generated).expect("failed to write embedded lib table");
}

/// Returns the normalized lib names (`es5`, `dom.iterable`, …) found in
/// `lib_dir`, derived from `lib.<name>.d.ts` filenames.
fn collect_lib_files(lib_dir: &Path) -> Vec<String> {
    let Ok(entries) = fs::read_dir(lib_dir) else {
        panic!(
            "vendored TypeScript libs are missing at {}; run `pnpm run lib:generate`",
            lib_dir.display()
        );
    };

    let mut libs = Vec::new();
    for entry in entries.flatten() {
        let file_name = entry.file_name();
        let file_name = file_name.to_string_lossy();
        let Some(rest) = file_name.strip_prefix("lib.") else {
            continue;
        };
        let Some(name) = rest.strip_suffix(".d.ts") else {
            continue;
        };
        if !name.is_empty() {
            libs.push(name.to_string());
        }
    }

    assert!(
        !libs.is_empty(),
        "no lib.*.d.ts files found in {}; run `pnpm run lib:generate`",
        lib_dir.display()
    );
    libs
}

/// Reads `generatedFrom.typescriptPackageVersion` out of the vendor manifest.
///
/// The manifest is written by the vendor-update script and is the single place
/// the bundled TypeScript version is recorded, so the build fails loudly rather
/// than reporting a version the snapshot did not come from.
fn read_pinned_version(manifest_path: &Path) -> String {
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let manifest = fs::read_to_string(manifest_path).unwrap_or_else(|error| {
        panic!(
            "failed to read {}: {error}; run `pnpm run lib:generate`",
            manifest_path.display()
        )
    });

    let key = "\"typescriptPackageVersion\"";
    let after_key = manifest
        .find(key)
        .map(|idx| &manifest[idx + key.len()..])
        .and_then(|rest| rest.split_once(':'))
        .map(|(_, rest)| rest);
    let version = after_key
        .and_then(|rest| rest.split_once('"'))
        .and_then(|(_, rest)| rest.split_once('"'))
        .map(|(version, _)| version.trim().to_string());

    version.unwrap_or_else(|| {
        panic!(
            "{} has no generatedFrom.typescriptPackageVersion entry",
            manifest_path.display()
        )
    })
}
