#!/usr/bin/env python3
"""Generates kind.rs and messages.rs for crates/surge-ts-tsc-syntax from a
typescript-go checkout (tsc/internal). Usage: generate.py <tsc/internal dir>"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1])
out = pathlib.Path(__file__).resolve().parents[2] / 'crates/surge-ts-tsc-syntax/src'

src = (root / 'ast/kind_generated.go').read_text()
block = src[src.index('const (') : src.index('\n)\n', src.index('const ('))]
kinds, markers = [], []
for line in block.splitlines():
    line = line.split('//', 1)[0].strip()
    m = re.fullmatch(r'Kind(\w+)(?:\s+Kind\s*=\s*iota)?', line)
    if m:
        kinds.append(m.group(1)); continue
    m = re.fullmatch(r'Kind(\w+)\s*=\s*Kind(\w+)', line)
    if m:
        markers.append((m.group(1), m.group(2)))
lines = ['// Generated by scripts/tsc-syntax/generate.py from typescript-go ast/kind_generated.go. Do not edit.', '',
         '#[allow(dead_code)]', '#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Default)]', '#[repr(u16)]', 'pub enum Kind {']
for i, k in enumerate(kinds):
    lines.append(f'    {"#[default] " if i == 0 else ""}{k},')
lines += ['}', '', '#[allow(non_upper_case_globals, dead_code)]', 'impl Kind {']
for name, target in markers:
    lines.append(f'    pub const {name}: Kind = Kind::{target};')
lines += ['', '    pub const ALL: [Kind; ' + str(len(kinds)) + '] = [' + ', '.join(f'Kind::{k}' for k in kinds) + '];', '}', '']
(out / 'kind.rs').write_text('\n'.join(lines))

# Messages referenced by the parser, scanner (with its regular expression
# validator) and binder, by the checker's
# merge of the global symbol table (initializeChecker, mergeSymbol), and by its
# unused-identifier check (checkUnusedIdentifiers).
used = set()
for f in ['parser/parser.go', 'parser/utilities.go', 'parser/references.go', 'scanner/scanner.go', 'scanner/regexp.go', 'scanner/utilities.go', 'ast/utilities.go', 'binder/binder.go']:
    used |= set(re.findall(r'diagnostics\.(\w+)', (root / f).read_text()))
used |= {'Declaration_name_conflicts_with_built_in_global_identifier_0'}
used |= {'X_0_is_declared_but_its_value_is_never_read', 'X_0_is_declared_but_never_used',
         'Property_0_is_declared_but_its_value_is_never_read', 'All_imports_in_import_declaration_are_unused',
         'All_destructured_elements_are_unused', 'All_variables_are_unused', 'All_type_parameters_are_unused'}
diag = (root / 'diagnostics/diagnostics_generated.go').read_text()
def rust_str(s):
    out = []
    for ch in s:
        if ch == '"': out.append('\\"')
        elif ch == '\\': out.append('\\\\')
        elif ch == '\n': out.append('\\n')
        elif ord(ch) < 0x20 or ord(ch) > 0x7e: out.append('\\u{%x}' % ord(ch))
        else: out.append(ch)
    return '"' + ''.join(out) + '"'
msgs = []
for m in re.finditer(r'^var (\w+) = &Message\{code: (\d+), category: Category(\w+), key: "(?:[^"\\]|\\.)*", text: ("(?:[^"\\]|\\.)*")', diag, re.M):
    name, code, cat, text = m.groups()
    if name in used:
        msgs.append((name, int(code), cat, bytes(text[1:-1], 'utf-8').decode('unicode_escape')))
missing = used - {m[0] for m in msgs} - {'Message'}
lines = ['// Generated by scripts/tsc-syntax/generate.py from typescript-go diagnostics_generated.go. Do not edit.', '',
         'use crate::Message;', '']
for name, code, cat, text in sorted(msgs, key=lambda m: m[1]):
    lines.append(f'#[allow(non_upper_case_globals, dead_code)]\npub const {name}: &Message = &Message {{ code: {code}, text: {rust_str(text)} }};')
(out / 'messages.rs').write_text('\n'.join(lines) + '\n')
print(len(kinds), 'kinds', len(markers), 'markers', len(msgs), 'messages; unresolved:', sorted(missing))
