// Generates the compiler API's enum tables from typescript@6.0.3, the last
// release of TypeScript's JavaScript compiler API, so `ts.SyntaxKind`,
// `ts.TypeFlags` and friends carry the values and reverse mappings its users
// know.
//
// Usage: node_modules/.bin/tsx scripts/api/generate-enums.ts
// Writes crates/surge-ts/src/api/enums_generated.rs, and the npm package's
// node guards (lib/guards.cjs) and type declarations (index.d.ts over a copy
// of typescript@6.0.3's lib/typescript.d.ts).

import { copyFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript-6";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const ENUMS = [
	"SyntaxKind",
	"NodeFlags",
	"ModifierFlags",
	"TokenFlags",
	"TypeFlags",
	"ObjectFlags",
	"SymbolFlags",
	"SignatureKind",
	"DiagnosticCategory",
	"ScriptTarget",
	"ScriptKind",
	"ModuleKind",
	"ModuleResolutionKind",
	"ModuleDetectionKind",
	"JsxEmit",
	"NewLineKind",
	"LanguageVariant",
	"TypeFormatFlags",
	"Extension",
] as const;

// tsgo's names for the kinds whose names differ from TypeScript 6's. Kinds
// only typescript-go has (its JSDoc reparse nodes, a keyword TypeScript 6
// lacks) have no TypeScript 6 kind and map to `Unknown`; this port never
// produces them.
const TSGO_RENAMES: Record<string, string> = {
	EndOfFile: "EndOfFileToken",
	JSDocUnknownTag: "JSDocTag",
};
const TSGO_ONLY = new Set(["ImmediateKeyword", "JSTypeAliasDeclaration", "JSImportDeclaration", "Count"]);

function entries(name: (typeof ENUMS)[number]): [string, number | string][] {
	const object = (ts as unknown as Record<string, Record<string, number | string>>)[name];
	return Object.entries(object).filter(([key]) => Number.isNaN(Number(key))) as [string, number | string][];
}

const kindSource = readFileSync(join(root, "crates/surge-ts-tsc-syntax/src/kind.rs"), "utf8");
const enumStart = kindSource.indexOf("pub enum Kind {") + "pub enum Kind {".length;
const tsgoKinds = kindSource
	.slice(enumStart, kindSource.indexOf("}", enumStart))
	.split("\n")
	.map((line) => line.trim().replace(/^#\[default\]\s*/, "").replace(/,$/, ""))
	.filter(Boolean);

const syntaxKinds = entries("SyntaxKind") as [string, number][];
const canonical = new Map<number, string>();
for (const [name, value] of syntaxKinds) if (!canonical.has(value)) canonical.set(value, name);
const syntaxKindValue = new Map(syntaxKinds);

let out = `// Generated by scripts/api/generate-enums.ts from typescript@${ts.version}. Do not edit.\n\n`;
out += "use surge_ts_tsc_syntax::Kind;\n\n";

out += "/// TypeScript's `SyntaxKind`, numbered as typescript@6.0.3 numbers it.\n";
out += "#[allow(non_upper_case_globals)]\n";
out += "#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]\n";
out += "pub struct SyntaxKind(pub u16);\n\n";
out += "#[allow(non_upper_case_globals)]\nimpl SyntaxKind {\n";
for (const [name, value] of syntaxKinds) out += `    pub const ${name}: SyntaxKind = SyntaxKind(${value});\n`;
out += "\n    /// The kind's name, as `ts.SyntaxKind[kind]` gives it for its first-declared name.\n";
out += "    pub fn name(self) -> &'static str {\n        match self.0 {\n";
for (const [value, name] of canonical) out += `            ${value} => "${name}",\n`;
out += '            _ => "Unknown",\n        }\n    }\n}\n\n';

out += "/// The TypeScript kind of a node of this port's `kind`.\n";
out += "pub(crate) fn syntax_kind_of(kind: Kind) -> SyntaxKind {\n    match kind {\n";
for (const tsgo of tsgoKinds) {
	if (TSGO_ONLY.has(tsgo)) continue;
	const tsName = TSGO_RENAMES[tsgo] ?? tsgo;
	if (!syntaxKindValue.has(tsName)) throw new Error(`no TypeScript 6 kind for tsgo ${tsgo}`);
	out += `        Kind::${tsgo} => SyntaxKind::${tsName},\n`;
}
out += "        _ => SyntaxKind::Unknown,\n    }\n}\n\n";

out += "/// Every enum the compiler API exports, as `(name, entries)` in the order\n";
out += "/// TypeScript declares them, so a JavaScript enum object rebuilt from them\n";
out += "/// has TypeScript's forward and reverse mappings.\n";
out += "pub enum EnumValue {\n    Number(f64),\n    String(&'static str),\n}\n\n";
out += "pub static ENUMS: &[(&str, &[(&str, EnumValue)])] = &[\n";
for (const name of ENUMS) {
	out += `    ("${name}", &[\n`;
	for (const [key, value] of entries(name)) {
		out += typeof value === "number"
			? `        ("${key}", EnumValue::Number(${Number.isInteger(value) ? `${value}.0` : value})),\n`
			: `        ("${key}", EnumValue::String(${JSON.stringify(value)})),\n`;
	}
	out += "    ]),\n";
}
out += "];\n\n";

const consts = (name: string, rustType: string) => {
	let block = `#[allow(non_upper_case_globals, dead_code)]\npub mod ${name
		.replace(/([a-z])([A-Z])/g, "$1_$2")
		.toLowerCase()} {\n`;
	for (const [key, value] of entries(name as (typeof ENUMS)[number])) {
		block += `    pub const ${key}: ${rustType} = ${value as number};\n`;
	}
	return block + "}\n\n";
};
out += "/// TypeScript's `TypeFlags`.\n" + consts("TypeFlags", "i32");
out += "/// TypeScript's `ObjectFlags`.\n" + consts("ObjectFlags", "i32");
out += "/// TypeScript's `SymbolFlags`.\n" + consts("SymbolFlags", "i32");
out += "/// TypeScript's `NodeFlags`.\n" + consts("NodeFlags", "i32");
out += "/// TypeScript's `ModifierFlags`.\n" + consts("ModifierFlags", "i32");
out += "/// TypeScript's `ScriptTarget`.\n" + consts("ScriptTarget", "i32");
out += "/// TypeScript's `ModuleKind`.\n" + consts("ModuleKind", "i32");
out += "/// TypeScript's `ModuleResolutionKind`.\n" + consts("ModuleResolutionKind", "i32");
out += "/// TypeScript's `ModuleDetectionKind`.\n" + consts("ModuleDetectionKind", "i32");
out += "/// TypeScript's `JsxEmit`.\n" + consts("JsxEmit", "i32");
out += "/// TypeScript's `ScriptKind`.\n" + consts("ScriptKind", "i32");

writeFileSync(join(root, "crates/surge-ts/src/api/enums_generated.rs"), out);
console.log(`wrote enums_generated.rs (${syntaxKinds.length} SyntaxKind names)`);

// TypeScript's node type guards that are kind tests (`isIdentifier`,
// `isStringLiteralLike`, ...): found by probing each exported `is*` function
// with a bare `{ kind }` for every kind; a guard true for at least one kind,
// false for the rest and never throwing is a kind-set test.
const kindValues = [...new Set(syntaxKinds.map(([, value]) => value))];
const declarations = readFileSync(join(root, "node_modules/typescript-6/lib/typescript.d.ts"), "utf8");
const publicGuards = new Set([...declarations.matchAll(/function (is[A-Z]\w*)\(node: Node\): node is/g)].map((match) => match[1]));
const guards: Record<string, number[]> = {};
for (const [name, value] of Object.entries(ts as unknown as Record<string, unknown>)) {
	if (!publicGuards.has(name) || typeof value !== "function" || value.length !== 1) continue;
	const accepted: number[] = [];
	let valid = true;
	for (const kind of kindValues) {
		try {
			const result = (value as (node: unknown) => unknown)({ kind, flags: 0, parent: undefined });
			if (result === true) accepted.push(kind);
			else if (result !== false) valid = false;
		} catch {
			valid = false;
		}
		if (!valid) break;
	}
	if (valid && accepted.length > 0 && accepted.length < kindValues.length / 2) guards[name] = accepted;
}
let guardsOut = `// Generated by scripts/api/generate-enums.ts from typescript@${ts.version}. Do not edit.\n`;
guardsOut += "// TypeScript's node kind guards: each accepts exactly these `SyntaxKind`s.\n";
guardsOut += `"use strict";\n\nmodule.exports = ${JSON.stringify(guards, null, "\t")};\n`;
writeFileSync(join(root, "packages/surge-ts/lib/guards.cjs"), guardsOut);
console.log(`wrote guards.cjs (${Object.keys(guards).length} guards)`);

// The package's types. typescript@7 ships no declarations for the JavaScript
// API, so the package carries typescript@6.0.3's (Apache-2.0, header kept)
// and re-exports every type of it, but only the values surge-ts provides:
// an API surge-ts lacks is a type error rather than a runtime surprise.
const SUPPORTED_VALUES = new Set<string>([
	"version",
	"versionMajorMinor",
	"sys",
	"createProgram",
	"createSourceFile",
	"createCompilerHost",
	"getDefaultLibFileName",
	"getPreEmitDiagnostics",
	"forEachChild",
	"getLineAndCharacterOfPosition",
	"getPositionOfLineAndCharacter",
	"computeLineStarts",
	"computeLineAndCharacterOfPosition",
	"getLineStarts",
	"escapeLeadingUnderscores",
	"unescapeLeadingUnderscores",
	"idText",
	"symbolName",
	"readConfigFile",
	"parseConfigFileTextToJson",
	"parseJsonConfigFileContent",
	"findConfigFile",
	"getParsedCommandLineOfConfigFile",
	"resolveModuleName",
	"flattenDiagnosticMessageText",
	"formatDiagnostic",
	"formatDiagnostics",
	"formatDiagnosticsWithColorAndContext",
	"sortAndDeduplicateDiagnostics",
	"diagnosticCategoryName",
	...ENUMS,
	...Object.keys(guards),
]);
const declarationFile = join(root, "node_modules/typescript-6/lib/typescript.d.ts");
copyFileSync(declarationFile, join(root, "packages/surge-ts/lib/typescript.d.ts"));
const declarationProgram = ts.createProgram([declarationFile], { noEmit: true });
const declarationChecker = declarationProgram.getTypeChecker();
const declarationModule = declarationChecker.getSymbolAtLocation(declarationProgram.getSourceFile(declarationFile)!)!;
const members: string[] = [];
for (const symbol of declarationChecker.getExportsOfModule(declarationModule)) {
	const name = symbol.getName();
	const flags = symbol.getFlags();
	const isValue = (flags & ts.SymbolFlags.Value) !== 0;
	const isType = (flags & ts.SymbolFlags.Type) !== 0;
	if (SUPPORTED_VALUES.has(name) || (isType && !isValue)) {
		members.push(`    export import ${name} = ts.${name};`);
	} else if (isType && !(flags & ts.SymbolFlags.Class)) {
		// A type whose value surge-ts lacks (an enum it does not provide).
		members.push(`    export type ${name} = ts.${name};`);
	}
}
let typesOut = `// Generated by scripts/api/generate-enums.ts from typescript@${ts.version}. Do not edit.\n`;
typesOut += "// The surge-ts package: TypeScript's compiler API types (lib/typescript.d.ts),\n";
typesOut += "// with the values limited to those surge-ts provides. docs/COMPILER_API.md\n";
typesOut += "// lists what each one supports.\n";
typesOut += `import ts = require("./lib/typescript");\n\ndeclare namespace surge {\n${members.join("\n")}\n}\n\nexport = surge;\n`;
writeFileSync(join(root, "packages/surge-ts/index.d.ts"), typesOut);
console.log(`wrote index.d.ts (${members.length} members)`);
