// ESM entry: `import ts from "surge-ts"` or named imports.
import ts from "./index.cjs";

export default ts;
export const {
	version,
	sys,
	SyntaxKind,
	NodeFlags,
	ModifierFlags,
	TokenFlags,
	TypeFlags,
	ObjectFlags,
	SymbolFlags,
	SignatureKind,
	DiagnosticCategory,
	ScriptTarget,
	ScriptKind,
	ModuleKind,
	ModuleResolutionKind,
	ModuleDetectionKind,
	JsxEmit,
	NewLineKind,
	LanguageVariant,
	TypeFormatFlags,
	Extension,
	createProgram,
	createSourceFile,
	createCompilerHost,
	getPreEmitDiagnostics,
	forEachChild,
	readConfigFile,
	parseConfigFileTextToJson,
	parseJsonConfigFileContent,
	findConfigFile,
	getParsedCommandLineOfConfigFile,
	resolveModuleName,
	flattenDiagnosticMessageText,
	formatDiagnostic,
	formatDiagnostics,
	formatDiagnosticsWithColorAndContext,
} = ts;
